/**
 * Direct Oisy signer integration using @icp-sdk/signer v5.
 *
 * Migrated from @slide-computer/signer v4 on 2026-05-21. Thomas Gladdines
 * (author of both libs, now at DFINITY) confirmed that ICRC-112 batching
 * was never adopted by wallets — @slide-computer faked batch() by issuing
 * sequential ICRC-49 calls under the hood. This caused the intermittent
 * `_arr` undefined errors we saw between sequential calls (Principal type
 * mismatch in Oisy v2.0.0's switch from @icp-sdk/auth v4 to v6).
 *
 * The v5 lib has no batch/commit/execute. Each canister call is independent.
 * Multiple sequential awaits open one Oisy popup window and surface as
 * separate consent screens within it.
 *
 * The SignerAgent.create() method returns an Agent (drop-in HttpAgent) that
 * can be passed to @dfinity/agent's Actor.createActor().
 *
 * Usage:
 *   const signerAgent = await getOisySignerAgent(principal);
 *   const actor = createOisyActor(canisterId, idlFactory, signerAgent);
 *   await actor.icrc2_approve(...);   // first consent screen
 *   await actor.deposit(...);          // second consent screen
 */

import { Signer } from '@icp-sdk/signer';
import { SignerAgent } from '@icp-sdk/signer/agent';
import { PostMessageTransport } from '@icp-sdk/signer/web';
import { Principal as IcpSdkPrincipal } from '@icp-sdk/core/principal';
import { Actor } from '@dfinity/agent';
import type { Principal } from '@dfinity/principal';

// Module-level Signer. Lightweight — no popup until first signing request.
// windowOpenerFeatures shapes Oisy as a popup window rather than a tab.
const oisySigner = new Signer({
  transport: new PostMessageTransport({
    url: 'https://oisy.com/sign',
    windowOpenerFeatures: 'toolbar=0,location=0,menubar=0,width=525,height=705',
  }),
});

let cachedAgent: any = null;
let cachedPrincipalText: string | null = null;
let preWarmedFor: string | null = null;

/**
 * Get or create a v5 SignerAgent for the given principal.
 *
 * The agent is cached across mutations within a session. Creating it does NOT
 * open a popup — the popup opens on the first canister call routed through it.
 *
 * Returns the raw v5 SignerAgent (no Proxy wrapping). The earlier Proxy-based
 * compat shim that no-op'd batch()/execute() was removed once Phase 2 of the
 * migration converted all call sites to plain sequential awaits — the Proxy
 * broke methods that access the class's `#private` fields (the v5 SignerAgent
 * uses ES private slots internally, and Proxy + `#private` is incompatible
 * because `this` inside the method becomes the Proxy, not the real instance).
 *
 * @param principal Dfinity Principal of the connected account
 * @returns A SignerAgent compatible with @dfinity/agent Actor.createActor()
 */
export async function getOisySignerAgent(principal: Principal): Promise<any> {
  const principalText = principal.toText();

  if (cachedAgent && cachedPrincipalText === principalText) {
    return cachedAgent;
  }

  // Convert @dfinity/principal → @icp-sdk/core/principal via text representation.
  // The two libs have separate Principal classes; passing one to the other
  // directly causes a `_arr` mismatch (the v4-era bug).
  const sdkPrincipal = IcpSdkPrincipal.fromText(principalText);

  cachedAgent = await SignerAgent.create({
    signer: oisySigner,
    account: sdkPrincipal,
  });

  cachedPrincipalText = principalText;
  return cachedAgent;
}

/**
 * Best-effort pre-warm of the Oisy signer agent so the cached agent is ready
 * before the user clicks a write action (mint, borrow, repay, deposit, etc.).
 *
 * Creating the agent does NOT open a popup (only the first canister call routed
 * through it does), so this is safe to call on wallet connect. Pre-warming
 * removes the cold-cache `SignerAgent.create()` handshake from the click path —
 * that handshake is network I/O which consumes the browser's user-gesture
 * window and trips Oisy's "Signer window should not be opened outside of click
 * handler" guard before the first consent screen can open.
 *
 * Idempotent per principal. Failures are swallowed: a failed pre-warm just
 * means the click path falls back to a cold create, exactly as before.
 */
export async function preWarmOisySigner(principal: Principal): Promise<void> {
  const principalText = principal.toText();
  if (preWarmedFor === principalText && cachedAgent) return;
  try {
    await getOisySignerAgent(principal);
    preWarmedFor = principalText;
  } catch {
    preWarmedFor = null;
  }
}

/**
 * Create an actor that routes calls through the v5 SignerAgent.
 * Drop-in @dfinity/agent Actor — supports any IDL factory generated by didc.
 *
 * The `agent: signerAgent as any` cast is intentional: v5's SignerAgent and
 * @dfinity/agent's HttpAgent are siblings, not identical types. Same pattern
 * we used with v4.
 */
export function createOisyActor(
  canisterId: string,
  idlFactory: any,
  signerAgent: any,
): any {
  return Actor.createActor(idlFactory, {
    agent: signerAgent as any,
    canisterId,
  });
}

/**
 * Clear cached signer agent (call on wallet disconnect).
 */
export function clearOisySigner(): void {
  cachedAgent = null;
  cachedPrincipalText = null;
  preWarmedFor = null;
}
