/**
 * Direct Oisy signer integration using @icp-sdk/signer v5.
 *
 * Migrated from @slide-computer/signer v4 on 2026-05-21. Thomas Gladdines
 * (author of both libs, now at DFINITY) confirmed that ICRC-112 batching
 * was never adopted by wallets — @slide-computer faked batch() by issuing
 * sequential ICRC-49 calls under the hood. This caused the intermittent
 * `_arr` undefined errors we saw between sequential calls (Principal type
 * mismatch in Oisy v2.0.0's switch from @icp-sdk/auth v4 to v6).
 *
 * The v5 lib has no batch/commit/execute. Each canister call is independent.
 * Multiple sequential awaits open one Oisy popup window and surface as
 * separate consent screens within it.
 *
 * The SignerAgent.create() method returns an Agent (drop-in HttpAgent) that
 * can be passed to @dfinity/agent's Actor.createActor().
 *
 * Usage:
 *   const signerAgent = await getOisySignerAgent(principal);
 *   const actor = createOisyActor(canisterId, idlFactory, signerAgent);
 *   await actor.icrc2_approve(...);   // first consent screen
 *   await actor.deposit(...);          // second consent screen
 */

import { Signer } from '@icp-sdk/signer';
import { SignerAgent } from '@icp-sdk/signer/agent';
import { PostMessageTransport } from '@icp-sdk/signer/web';
import { Principal as IcpSdkPrincipal } from '@icp-sdk/core/principal';
import { Actor } from '@dfinity/agent';
import type { Principal } from '@dfinity/principal';

// Module-level Signer. Lightweight — no popup until first signing request.
// windowOpenerFeatures shapes Oisy as a popup window rather than a tab.
const oisySigner = new Signer({
  transport: new PostMessageTransport({
    url: 'https://oisy.com/sign',
    windowOpenerFeatures: 'toolbar=0,location=0,menubar=0,width=525,height=705',
  }),
});

let cachedAgent: any = null;
let cachedPrincipalText: string | null = null;

/**
 * Get or create a v5 SignerAgent for the given principal.
 *
 * The agent is cached across mutations within a session. Creating it does NOT
 * open a popup — the popup opens on the first canister call routed through it.
 *
 * Returns a proxy that no-ops `batch()` and `execute()` so un-migrated call
 * sites continue to work during the v4 → v5 migration. The proxy is removed
 * in Phase 4 of the migration once all call sites are converted to plain
 * sequential awaits.
 *
 * @param principal Dfinity Principal of the connected account
 * @returns A SignerAgent compatible with @dfinity/agent Actor.createActor()
 */
export async function getOisySignerAgent(principal: Principal): Promise<any> {
  const principalText = principal.toText();

  if (cachedAgent && cachedPrincipalText === principalText) {
    return cachedAgent;
  }

  // Convert @dfinity/principal → @icp-sdk/core/principal via text representation.
  // The two libs have separate Principal classes; passing one to the other
  // directly causes a `_arr` mismatch (the v4-era bug).
  const sdkPrincipal = IcpSdkPrincipal.fromText(principalText);

  const realAgent = await SignerAgent.create({
    signer: oisySigner,
    account: sdkPrincipal,
  });

  cachedAgent = withCompatShim(realAgent);
  cachedPrincipalText = principalText;
  return cachedAgent;
}

/**
 * Create an actor that routes calls through the v5 SignerAgent.
 * Drop-in @dfinity/agent Actor — supports any IDL factory generated by didc.
 *
 * The `agent: signerAgent as any` cast is intentional: v5's SignerAgent and
 * @dfinity/agent's HttpAgent are siblings, not identical types. Same pattern
 * we used with v4.
 */
export function createOisyActor(
  canisterId: string,
  idlFactory: any,
  signerAgent: any,
): any {
  return Actor.createActor(idlFactory, {
    agent: signerAgent as any,
    canisterId,
  });
}

/**
 * Clear cached signer agent (call on wallet disconnect).
 */
export function clearOisySigner(): void {
  cachedAgent = null;
  cachedPrincipalText = null;
}

// ─── Migration compat shim ──────────────────────────────────────────────────
//
// During the v4 → v5 migration, call sites still invoke
// `signerAgent.batch()` and `signerAgent.execute()`. The v4 library faked
// these as sequential ICRC-49 calls under the hood — they were never real
// atomic batches. v5 has no batch concept at all.
//
// We wrap the real v5 agent in a Proxy that no-ops batch/execute, letting
// us migrate the 91 call sites one file at a time without breaking
// un-migrated paths. Each call still goes through the v5 agent normally;
// the batch/execute "ceremony" is just stripped.
//
// Once all call sites are migrated (Phase 4), this shim and its logging
// helper are removed and `getOisySignerAgent` returns the raw agent.
// ────────────────────────────────────────────────────────────────────────────

let shimLogCount = 0;

function withCompatShim(realAgent: any): any {
  return new Proxy(realAgent, {
    get(target, prop, receiver) {
      if (prop === 'batch') {
        return () => {
          if (shimLogCount++ < 3) {
            console.debug(
              '[oisySigner v5 shim] batch() called — no-op. ' +
              'Migrate this call site to sequential awaits (Phase 2 of migration).'
            );
          }
        };
      }
      if (prop === 'execute') {
        return async () => {
          if (shimLogCount++ < 3) {
            console.debug(
              '[oisySigner v5 shim] execute() called — no-op. ' +
              'Migrate this call site to sequential awaits (Phase 2 of migration).'
            );
          }
        };
      }
      // Forward everything else to the real agent
      return Reflect.get(target, prop, receiver);
    },
  });
}
