<script lang="ts">
  import { onMount } from 'svelte';
  import { publicActor } from '$lib/services/protocol/apiClient';

  let interestPoolPct = '75';
  let liqProtocolPct = '3';

  onMount(async () => {
    try {
      const [poolShare, lpShare] = await Promise.all([
        publicActor.get_interest_pool_share() as Promise<number>,
        publicActor.get_liquidation_protocol_share() as Promise<number>,
      ]);
      interestPoolPct = (Number(poolShare) * 100).toFixed(0);
      liqProtocolPct = (Number(lpShare) * 100).toFixed(0);
    } catch (e) {
      console.error('Failed to fetch stability pool params:', e);
    }
  });
</script>

<svelte:head><title>Stability Pool - Rumi Docs</title></svelte:head>

<article class="doc-page">
  <h1 class="doc-title">Stability Pool</h1>

  <section class="doc-section">
    <h2 class="doc-heading">What Is the Stability Pool</h2>
    <p>The stability pool is the protocol's first line of defense against undercollateralized vaults. Users deposit icUSD into the pool, and when a vault is liquidated, the pool's icUSD is used to repay the vault's debt. In exchange, depositors receive the liquidated collateral at a discount (the liquidation bonus).</p>
    <p>The stability pool also receives {interestPoolPct}% of all interest revenue generated by the protocol. This interest is distributed to depositors as icUSD, proportional to their share of the pool.</p>
  </section>

  <section class="doc-section">
    <h2 class="doc-heading">How It Works</h2>
    <p>When you deposit icUSD into the stability pool, you become eligible to participate in liquidations. The process is:</p>
    <ol class="flow-list">
      <li>You deposit icUSD into the stability pool.</li>
      <li>When a vault becomes undercollateralized, anyone can trigger a liquidation against it using the pool.</li>
      <li>The pool's icUSD is used to repay the vault's debt. Your deposit is reduced proportionally.</li>
      <li>In return, the pool receives the vault's collateral (e.g., ICP) at a discount — the liquidation penalty means the collateral is worth more than the debt repaid.</li>
      <li>You can withdraw your remaining icUSD and any collateral gains at any time.</li>
    </ol>
  </section>

  <section class="doc-section">
    <h2 class="doc-heading">Earnings</h2>
    <p>Stability pool depositors earn from two sources:</p>
    <ul class="doc-list">
      <li><strong>Liquidation gains</strong> — when liquidations occur, you receive collateral worth more than the icUSD burned from your deposit. The difference (the liquidation penalty, minus the {liqProtocolPct}% protocol fee) is your profit.</li>
      <li><strong>Interest revenue</strong> — {interestPoolPct}% of all interest accrued on vault debt is minted as icUSD and distributed to stability pool depositors proportionally. This provides a steady yield even when no liquidations occur.</li>
    </ul>
  </section>

  <section class="doc-section">
    <h2 class="doc-heading">Risks</h2>
    <p><strong>Collateral price risk:</strong> When a liquidation occurs, you receive collateral (e.g., ICP) in exchange for icUSD. If the collateral's price drops further after you receive it, your gains could turn into losses. The liquidation bonus provides a buffer, but a sharp continued decline can exceed it.</p>
    <p><strong>Deposit reduction:</strong> Each liquidation reduces your icUSD deposit. If many vaults are liquidated in quick succession, a large portion of your deposit could be converted to collateral. You are not guaranteed to get your original icUSD amount back.</p>
    <p><strong>Smart contract risk:</strong> The stability pool is a separate canister from the main protocol. It carries its own smart contract risk. See the <a href="/docs/beta" class="doc-link">beta disclaimer</a>.</p>
  </section>

  <section class="doc-section">
    <h2 class="doc-heading">Depositing and Withdrawing</h2>
    <p>You can deposit icUSD into the stability pool at any time via the <a href="/stability-pool" class="doc-link">Stability Pool</a> page. Withdrawals are also available at any time — there is no lock-up period. When you withdraw, you receive your remaining icUSD deposit plus any accumulated collateral from liquidations.</p>
    <p>If you are using the <strong>Oisy</strong> wallet, deposits and withdrawals are batched into a single signer popup via ICRC-112 for a smoother experience.</p>
  </section>
</article>

<style>
  .flow-list {
    padding-left: 1.25rem;
    display: flex; flex-direction: column; gap: 0.5rem;
    margin: 0.5rem 0;
  }
  .flow-list li {
    font-size: 0.875rem; color: var(--rumi-text-secondary); line-height: 1.5;
  }
  .doc-list {
    padding-left: 1.25rem;
    display: flex; flex-direction: column; gap: 0.35rem;
    margin: 0.5rem 0;
  }
  .doc-list li {
    font-size: 0.875rem; color: var(--rumi-text-secondary); line-height: 1.5;
  }
</style>
