<script lang="ts">
  import { onMount } from 'svelte';
  import { publicActor } from '$lib/services/protocol/apiClient';

  type InterestSplitEntry = { destination: string; bps: bigint };
  let interestSplit: InterestSplitEntry[] = [];
  let liqProtocolPct = '3';

  function splitPct(dest: string): string {
    const entry = interestSplit.find(s => s.destination === dest);
    return entry ? (Number(entry.bps) / 100).toFixed(0) + '%' : '—';
  }

  onMount(async () => {
    try {
      const [split, lpShare] = await Promise.all([
        publicActor.get_interest_split() as Promise<InterestSplitEntry[]>,
        publicActor.get_liquidation_protocol_share() as Promise<number>,
      ]);
      interestSplit = split;
      liqProtocolPct = (Number(lpShare) * 100).toFixed(0);
    } catch (e) {
      console.error('Failed to fetch stability pool params:', e);
    }
  });
</script>

<svelte:head><title>Stability Pool | Rumi Docs</title></svelte:head>

<article class="doc-page">
  <h1 class="doc-title">Stability Pool</h1>

  <section class="doc-section">
    <h2 class="doc-heading">What Is the Stability Pool</h2>
    <p>The stability pool is the protocol's first line of defense against undercollateralized vaults. Users deposit stablecoins into the pool, and when a vault is liquidated, the pool's funds are used to repay the vault's debt. In exchange, depositors receive the liquidated collateral at a discount (the liquidation bonus).</p>
    <p>The pool accepts three stablecoins: <strong>icUSD</strong>, <strong>ckUSDC</strong>, and <strong>ckUSDT</strong>. icUSD depositors also receive <span class="live">{splitPct('stability_pool')}</span> of all interest revenue generated by the protocol, distributed proportionally to their share of the pool.</p>
  </section>

  <section class="doc-section">
    <h2 class="doc-heading">How It Works</h2>
    <p>When you deposit stablecoins into the stability pool, you become eligible to participate in liquidations. The process is:</p>
    <ol class="flow-list">
      <li>You deposit icUSD, ckUSDC, and/or ckUSDT into the stability pool.</li>
      <li>When a vault becomes undercollateralized, anyone can trigger a liquidation against it using the pool.</li>
      <li>The pool's stablecoins are used to repay the vault's debt. ckUSDC and ckUSDT are used first, then icUSD. Your deposit is reduced proportionally.</li>
      <li>In return, the pool receives the vault's collateral (e.g., ICP) at a discount — the liquidation penalty means the collateral is worth more than the debt repaid.</li>
      <li>You can withdraw your remaining deposits and any collateral gains at any time.</li>
    </ol>
  </section>

  <section class="doc-section">
    <h2 class="doc-heading">Liquidation Priority</h2>
    <p>When a liquidation occurs, <strong>ckUSDC and ckUSDT deposits are consumed first</strong>, before any icUSD is touched. This means ckUSDC/ckUSDT depositors get priority access to discounted collateral from liquidations, while icUSD depositors are more protected from deposit reduction.</p>
    <p>The tradeoff: ckUSDC and ckUSDT depositors do not earn interest revenue — only icUSD depositors receive the <span class="live">{splitPct('stability_pool')}</span> interest share.</p>
  </section>

  <section class="doc-section">
    <h2 class="doc-heading">Collateral Opt-Out</h2>
    <p>By default, depositors are opted in to all collateral types (ICP, ckBTC, ckETH). You can <strong>opt out</strong> of specific collateral types to avoid exposure to liquidations involving that asset. When you opt out of a collateral type:</p>
    <ul class="doc-list">
      <li>Your deposit is not used to liquidate vaults of that collateral type.</li>
      <li>You do not receive collateral gains from those liquidations.</li>
      <li>You do not receive interest revenue generated by vaults of that collateral type.</li>
    </ul>
    <p>This lets you tailor your risk exposure — for example, opting out of a volatile collateral while still participating in liquidations for assets you're comfortable holding. Opting out reduces your effective APR since you forfeit interest from the excluded collateral types.</p>
  </section>

  <section class="doc-section">
    <h2 class="doc-heading">Earnings</h2>
    <p>Stability pool depositors earn from two sources:</p>
    <ul class="doc-list">
      <li><strong>Liquidation gains</strong> — when liquidations occur, you receive collateral worth more than the stablecoins burned from your deposit. The difference (the liquidation penalty, minus the {liqProtocolPct}% protocol fee) is your profit.</li>
      <li><strong>Interest revenue</strong> (icUSD only) — <span class="live">{splitPct('stability_pool')}</span> of all interest accrued on vault debt is minted as icUSD and distributed to icUSD depositors. Interest is calculated per collateral type: each type's interest goes to icUSD depositors who are opted in to that collateral, proportional to their icUSD balance. This means opting in to all collateral types maximizes your APR.</li>
    </ul>
  </section>

  <section class="doc-section">
    <h2 class="doc-heading">Risks</h2>
    <p><strong>Collateral price risk:</strong> When a liquidation occurs, you receive collateral (e.g., ICP) in exchange for stablecoins. If the collateral's price drops further after you receive it, your gains could turn into losses. The liquidation bonus provides a buffer, but a sharp continued decline can exceed it.</p>
    <p><strong>Deposit reduction:</strong> Each liquidation reduces your stablecoin deposit. If many vaults are liquidated in quick succession, a large portion of your deposit could be converted to collateral. You are not guaranteed to get your original deposit amount back.</p>
    <p><strong>Concentration risk:</strong> If few icUSD depositors are opted in to a particular collateral type, those depositors bear a larger share of that collateral's liquidation exposure — but also earn a larger share of its interest revenue.</p>
    <p><strong>Smart contract risk:</strong> The stability pool is a separate canister from the main protocol. It carries its own smart contract risk. See the <a href="/docs/beta" class="doc-link">beta disclaimer</a>.</p>
  </section>

  <section class="doc-section">
    <h2 class="doc-heading">Depositing and Withdrawing</h2>
    <p>You can deposit icUSD, ckUSDC, or ckUSDT into the stability pool at any time via the <a href="/stability-pool" class="doc-link">Stability Pool</a> page. You can deposit multiple stablecoins simultaneously. Withdrawals are also available at any time — there is no lock-up period. When you withdraw, you receive your remaining stablecoin deposits plus any accumulated collateral from liquidations.</p>
    <p>If you are using the <strong>Oisy</strong> wallet, deposits and withdrawals are batched into a single signer popup via ICRC-112 for a smoother experience.</p>
  </section>
</article>

<style>
  .flow-list {
    padding-left: 1.25rem;
    display: flex; flex-direction: column; gap: 0.5rem;
    margin: 0.5rem 0;
  }
  .flow-list li {
    font-size: 0.875rem; color: var(--rumi-text-secondary); line-height: 1.5;
  }
  .doc-list {
    padding-left: 1.25rem;
    display: flex; flex-direction: column; gap: 0.35rem;
    margin: 0.5rem 0;
  }
  .doc-list li {
    font-size: 0.875rem; color: var(--rumi-text-secondary); line-height: 1.5;
  }
  .live { color: var(--rumi-action); font-weight: 600; }
</style>
